/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xemgsabpjuroeqbbvhis"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbWdzYWJwanVyb2VxYmJ2aGlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODkzMDYsImV4cCI6MjA3MTQ2NTMwNn0.lie5v7-r8uPvLOPEyIuieLiPmnAr9gGiYI-1rUSZxXI"